import type { Analysis, Finding, Severity } from "../core/schema.js";
import type { z } from "zod";
import { STATUS_LABEL, usableEndpoints } from "./format.js";

type Sev = z.infer<typeof Severity>;
const SEVERITY_ORDER: Record<Sev, number> = { high: 0, medium: 1, low: 2 };

function cell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/[\r\n]+/g, " ");
}

function sourcesInline(f: Finding<unknown>): string {
  if (!f.sources.length) return "—";
  return f.sources.map((s) => `[${new URL(s.url).pathname || "/"}](${s.url})`).join(", ");
}

function evidence(f: Finding<unknown>): string[] {
  const out = [`**Status:** ${STATUS_LABEL[f.status]}`];
  for (const s of f.sources) {
    out.push(s.quote ? `> "${s.quote.replace(/\n/g, " ")}"\n> — [${s.url}](${s.url})` : `Source: [${s.url}](${s.url})`);
  }
  if (f.reasoning) out.push(`_Reasoning:_ ${f.reasoning}`);
  return out;
}

function section(title: string, f: Finding<unknown>, describe: () => string[]): string[] {
  const body = f.status === "not_found" || f.value === null ? ["Not found in docs."] : describe();
  return [`### ${title}`, "", ...body, "", ...evidence(f), ""];
}

/** Human-readable integration summary (analysis.md). */
export function buildMarkdown(a: Analysis): string {
  const endpoints = usableEndpoints(a);
  const glance: [string, Finding<unknown>, string][] = [
    ["Base URL", a.baseUrl, a.baseUrl.value ?? ""],
    ["Authentication", a.auth, a.auth.value ? `${a.auth.value.type}: ${a.auth.value.description}` : ""],
    ["Pagination", a.pagination, a.pagination.value ? `${a.pagination.value.style}: ${a.pagination.value.description}` : ""],
    ["Rate limits", a.rateLimits, a.rateLimits.value?.limits ?? ""],
    ["Webhooks", a.webhooks, a.webhooks.value ? (a.webhooks.value.supported ? `Yes: ${a.webhooks.value.events.join(", ")}` : "Not supported") : ""],
    ["Error format", a.errorFormat, a.errorFormat.value?.description ?? ""],
    ["Versioning", a.versioning, a.versioning.value ? `${a.versioning.value.scheme}${a.versioning.value.current ? ` (${a.versioning.value.current})` : ""}` : ""],
  ];

  const risks = [...a.risks].sort((x, y) => SEVERITY_ORDER[x.severity] - SEVERITY_ORDER[y.severity]);
  const r = a.run;

  const lines = [
    `# ${a.apiName}: integration analysis`,
    "",
    `> Generated by API Integration Scout from <${a.docsUrl}> on ${a.generatedAt}.`,
    `> Every finding is marked **Documented** (quoted from the docs and verified), **Inferred** (the agent's reasoning) or **Not found in docs**.`,
    "",
    a.summary,
    "",
    "## At a glance",
    "",
    "| Area | Finding | Status | Source |",
    "| --- | --- | --- | --- |",
    ...glance.map(([area, f, v]) => `| ${area} | ${cell(f.status === "not_found" ? "—" : v)} | ${STATUS_LABEL[f.status]} | ${sourcesInline(f)} |`),
    `| Endpoints | ${endpoints.length} found | ${endpoints.filter((e) => e.status === "documented").length} documented, ${endpoints.filter((e) => e.status === "inferred").length} inferred | — |`,
    "",
    "## Risks",
    "",
    ...(risks.length
      ? risks.map((x) => `- **${x.severity.toUpperCase()}**: ${x.title}. ${x.detail}${x.origin !== "agent" ? ` _(${x.origin} check)_` : ""}`)
      : ["No risks identified."]),
    "",
    "## Open questions",
    "",
    ...(a.openQuestions.length ? a.openQuestions.map((q) => `- ${q}`) : ["None."]),
    "",
    "## Details",
    "",
    ...section("Base URL", a.baseUrl, () => [`\`${a.baseUrl.value}\``]),
    ...section("Authentication", a.auth, () => {
      const v = a.auth.value!;
      return [`- Type: ${v.type}`, ...(v.location ? [`- Location: ${v.location}`] : []), ...(v.parameterName ? [`- Parameter: \`${v.parameterName}\``] : []), `- ${v.description}`];
    }),
    "### Endpoints",
    "",
    ...(endpoints.length
      ? [
          "| Method | Path | Purpose | Key params | Status | Source |",
          "| --- | --- | --- | --- | --- | --- |",
          ...endpoints.map((e) => {
            const params = e.value.keyParams.map((p) => `\`${p.name}\` (${p.in}${p.required ? ", required" : ""})`).join(", ") || "—";
            return `| ${e.value.method} | \`${cell(e.value.path)}\` | ${cell(e.value.purpose)} | ${cell(params)} | ${STATUS_LABEL[e.status]} | ${sourcesInline(e)} |`;
          }),
        ]
      : ["Not found in docs."]),
    "",
    ...section("Pagination", a.pagination, () => {
      const v = a.pagination.value!;
      return [`- Style: ${v.style}`, `- Parameters: ${v.parameters.map((p) => `\`${p}\``).join(", ") || "—"}`, `- ${v.description}`];
    }),
    ...section("Rate limits", a.rateLimits, () => {
      const v = a.rateLimits.value!;
      return [`- Limits: ${v.limits}`, `- Headers: ${v.headers.map((h) => `\`${h}\``).join(", ") || "—"}`, `- ${v.description}`];
    }),
    ...section("Webhooks", a.webhooks, () => {
      const v = a.webhooks.value!;
      return [
        `- Supported: ${v.supported ? "yes" : "no"}`,
        `- Events: ${v.events.map((e) => `\`${e}\``).join(", ") || "—"}`,
        `- Signature verification: ${v.signatureVerification ?? "not described"}`,
        `- ${v.description}`,
      ];
    }),
    ...section("Error format", a.errorFormat, () => {
      const v = a.errorFormat.value!;
      return [v.description, ...(v.example ? ["", "```json", v.example, "```"] : [])];
    }),
    ...section("Versioning", a.versioning, () => {
      const v = a.versioning.value!;
      return [`- Scheme: ${v.scheme}`, ...(v.current ? [`- Current: ${v.current}`] : []), `- ${v.description}`];
    }),
    "## Pages visited",
    "",
    ...a.pagesVisited.map((p) => `- ${p.url}: ${p.status === "fetched" ? `${p.textLength} chars${p.lowText ? " (low text, may need JavaScript)" : ""}` : `failed (${p.error})`}`),
    "",
    ...(a.warnings.length ? ["## Warnings", "", ...a.warnings.map((w) => `- ${w}`), ""] : []),
    "## Run",
    "",
    `- Model: ${r.model}`,
    `- Turns: ${r.numTurns}, duration ${(r.durationMs / 1000).toFixed(1)}s`,
    `- Tokens: ${r.inputTokens} input, ${r.outputTokens} output, ${r.cacheCreationInputTokens} cache write, ${r.cacheReadInputTokens} cache read (${r.totalTokens} total)`,
    `- Estimated cost: $${r.costUsd.toFixed(4)}`,
    "",
  ];
  return lines.join("\n");
}
