import { randomUUID } from "node:crypto";
import type { Analysis, Endpoint, Finding } from "../core/schema.js";
import { STATUS_LABEL, baseUrlOf, endpointTarget, toPostmanPath, usableEndpoints, type EndpointTarget } from "./format.js";

export const POSTMAN_SCHEMA_URL = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json";

type KV = { key: string; value: string; type?: string };
type PostmanAuth = { type: string } & Record<string, KV[] | string>;

const BODY_METHODS = new Set(["POST", "PUT", "PATCH"]);

/**
 * Builds a Postman Collection v2.1. Credentials are only ever referenced as
 * {{apiKey}}; no value from the docs or the environment is written as a secret.
 */
export function buildPostmanCollection(analysis: Analysis, id: string = randomUUID()) {
  const endpoints = usableEndpoints(analysis);
  const baseUrl = baseUrlOf(analysis);
  const folders = new Map<string, ReturnType<typeof buildItem>[]>();
  for (const ep of endpoints) {
    const target = endpointTarget(ep.value.path, baseUrl);
    const folder =
      target.kind === "absolute" ? target.host : (target.path.split("/").find((s) => s && !s.startsWith("{")) ?? "root");
    folders.set(folder, [...(folders.get(folder) ?? []), buildItem(ep, target)]);
  }

  const auth = buildAuth(analysis);
  const notes = [
    analysis.summary,
    "",
    `Generated by API Integration Scout from ${analysis.docsUrl} on ${analysis.generatedAt}.`,
    "Set {{apiKey}} in the environment. Requests marked Inferred were not explicitly documented; check them before relying on them.",
  ];
  if (!auth) notes.push(`Authentication: ${describeAuthGap(analysis)}`);

  return {
    info: {
      _postman_id: id,
      name: `${analysis.apiName} (API Integration Scout)`,
      description: notes.join("\n"),
      schema: POSTMAN_SCHEMA_URL,
    },
    item: [...folders.entries()].map(([name, item]) => ({ name, item })),
    ...(auth ? { auth } : {}),
    variable: [
      { key: "baseUrl", value: baseUrlOf(analysis) ?? "", type: "string" },
      { key: "apiKey", value: "", type: "string" },
    ],
  };
}

function buildItem(ep: Finding<Endpoint> & { value: Endpoint }, target: EndpointTarget) {
  const { method, path, purpose, keyParams } = ep.value;
  const postmanPath = toPostmanPath(target.path);
  const hostPrefix = target.kind === "absolute" ? target.origin : "{{baseUrl}}";
  const segments = postmanPath.split("/").filter(Boolean);
  const query = keyParams
    .filter((p) => p.in === "query")
    .map((p) => ({ key: p.name, value: "", description: p.description, ...(p.required ? {} : { disabled: true }) }));
  const pathVars = keyParams.filter((p) => p.in === "path").map((p) => ({ key: p.name, value: "", description: p.description }));
  const headerParams = keyParams.filter((p) => p.in === "header").map((p) => ({ key: p.name, value: "", description: p.description }));
  const bodyParams = keyParams.filter((p) => p.in === "body");

  const queryString = query.filter((q) => !q.disabled).map((q) => `${q.key}=`).join("&");
  const raw = `${hostPrefix}${postmanPath}${queryString ? `?${queryString}` : ""}`;

  const header = [{ key: "Accept", value: "application/json" }, ...headerParams];
  const hasBody = BODY_METHODS.has(method);
  if (hasBody) header.push({ key: "Content-Type", value: "application/json" });

  const description = [
    purpose,
    "",
    `Status: ${STATUS_LABEL[ep.status]}`,
    ...(target.kind === "absolute" ? [`Note: this endpoint uses ${target.origin}, not {{baseUrl}}.`] : []),
    ...(ep.reasoning ? [`Reasoning: ${ep.reasoning}`] : []),
    ...ep.sources.map((s) => `Source: ${s.url}`),
  ].join("\n");

  return {
    name: `${method} ${path}${ep.status === "inferred" ? " (inferred)" : ""}`,
    request: {
      method,
      header,
      url: {
        raw,
        ...(target.kind === "absolute"
          ? { protocol: target.origin.split(":")[0]!.toLowerCase(), host: target.host.split(".") }
          : { host: ["{{baseUrl}}"] }),
        path: segments,
        ...(query.length ? { query } : {}),
        ...(pathVars.length ? { variable: pathVars } : {}),
      },
      ...(hasBody
        ? {
            body: {
              mode: "raw",
              raw: JSON.stringify(Object.fromEntries(bodyParams.map((p) => [p.name, `<${p.name}>`])), null, 2),
              options: { raw: { language: "json" } },
            },
          }
        : {}),
      description,
    },
  };
}

function buildAuth(analysis: Analysis): PostmanAuth | null {
  if (analysis.auth.status === "not_found" || !analysis.auth.value) return null;
  const { type, location, parameterName } = analysis.auth.value;
  switch (type) {
    case "api_key":
      return {
        type: "apikey",
        apikey: [
          { key: "key", value: parameterName || (location === "query" ? "api_key" : "X-API-Key"), type: "string" },
          { key: "value", value: "{{apiKey}}", type: "string" },
          { key: "in", value: location === "query" ? "query" : "header", type: "string" },
        ],
      };
    case "bearer":
      return { type: "bearer", bearer: [{ key: "token", value: "{{apiKey}}", type: "string" }] };
    case "basic":
      return {
        type: "basic",
        basic: [
          { key: "username", value: "{{apiKey}}", type: "string" },
          { key: "password", value: "", type: "string" },
        ],
      };
    case "oauth2":
      return {
        type: "oauth2",
        oauth2: [
          { key: "accessToken", value: "{{apiKey}}", type: "string" },
          { key: "addTokenTo", value: "header", type: "string" },
        ],
      };
    default:
      return null;
  }
}

function describeAuthGap(analysis: Analysis): string {
  if (analysis.auth.status === "not_found" || !analysis.auth.value) return "not found in docs; configure manually.";
  return `${analysis.auth.value.type}: ${analysis.auth.value.description} (configure manually).`;
}

/** Environment template: baseUrl is public and prefilled when known; every credential is empty. */
export function buildPostmanEnvironment(analysis: Analysis, id: string = randomUUID()) {
  return {
    id,
    name: `${analysis.apiName} (template)`,
    values: [
      { key: "baseUrl", value: baseUrlOf(analysis) ?? "", type: "default", enabled: true },
      { key: "apiKey", value: "", type: "secret", enabled: true },
    ],
    _postman_variable_scope: "environment",
  };
}
