import { randomUUID } from "node:crypto";
import { credentialParamKeys } from "../core/auth.js";
import { pathVariableExamples } from "../core/hosts.js";
import type { Analysis, Auth } from "../core/schema.js";
import {
  STATUS_LABEL,
  baseUrlOf,
  documentedAuthMethods,
  endpointTarget,
  toPostmanPath,
  usableEndpoints,
  type AuthMethod,
  type EndpointTarget,
  type UsableEndpoint,
} from "./format.js";

export const POSTMAN_SCHEMA_URL = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json";

type KV = { key: string; value: string; type?: string };
type PostmanAuth = { type: string } & Record<string, KV[] | string>;

const BODY_METHODS = new Set(["POST", "PUT", "PATCH"]);

/**
 * Builds a Postman Collection v2.1. Credentials are only ever referenced as
 * {{apiKey}}; no value from the docs or the environment is written as a secret.
 */
export function buildPostmanCollection(analysis: Analysis, id: string = randomUUID()) {
  const endpoints = usableEndpoints(analysis);
  const baseUrl = baseUrlOf(analysis);

  // Collection auth = the first documented method Postman can express; every
  // other documented method gets a sample request. Undocumented methods are never added.
  const methods = documentedAuthMethods(analysis);
  const primary = methods.find((m) => toPostmanAuth(m.value) !== null);
  const auth = primary ? toPostmanAuth(primary.value) : null;
  // Sample-able methods (incl. cookie API keys, which Postman's apikey auth can't express).
  const supported = methods.filter((m) => m === primary || ["api_key", "bearer", "basic", "oauth2"].includes(m.value.type));
  const credentialParams = credentialParamKeys(methods.map((m) => m.value));
  const apiJson = apiDocumentsJsonResponses(analysis);

  const folders = new Map<string, ReturnType<typeof buildItem>[]>();
  for (const ep of endpoints) {
    const target = endpointTarget(ep.value.path, baseUrl);
    const folder =
      target.kind === "absolute" ? target.host : (target.path.split("/").find((s) => s && !s.startsWith("{")) ?? "root");
    folders.set(folder, [...(folders.get(folder) ?? []), buildItem(ep, target, credentialParams, apiJson)]);
  }

  const items = [...folders.entries()].map(([name, item]) => ({ name, item }));
  const alternatives = supported.filter((m) => m !== primary).map((m) => buildAuthAlternative(m, endpoints, baseUrl, credentialParams, apiJson));
  if (alternatives.length) {
    items.push({ name: AUTH_ALTERNATIVES_FOLDER, item: alternatives });
  }

  const notes = [
    analysis.summary,
    "",
    `Generated by API Integration Scout from ${analysis.docsUrl} on ${analysis.generatedAt}.`,
    "Set {{apiKey}} in the environment. Requests marked Inferred were not explicitly documented; check them before relying on them.",
  ];
  if (primary) notes.push(`Authentication: ${authName(primary.value)} (documented).`);
  if (alternatives.length) notes.push(`Other documented auth methods: see the "${AUTH_ALTERNATIVES_FOLDER}" folder.`);
  const unsupported = methods.filter((m) => !supported.includes(m));
  for (const m of unsupported) notes.push(`Also documented, configure manually: ${m.value.type}: ${m.value.description}`);
  if (!primary) notes.push(`Authentication: ${describeAuthGap(analysis)}`);

  return {
    info: {
      _postman_id: id,
      name: `${analysis.apiName} (API Integration Scout)`,
      description: notes.join("\n"),
      schema: POSTMAN_SCHEMA_URL,
    },
    item: items,
    ...(auth ? { auth } : {}),
    variable: [
      { key: "baseUrl", value: baseUrl ?? "", type: "string" },
      { key: "apiKey", value: "", type: "string" },
      { key: "maxResponseMs", value: String(DEFAULT_MAX_RESPONSE_MS), type: "string" },
    ],
  };
}

export const AUTH_ALTERNATIVES_FOLDER = "Auth alternatives";
export const CHECK_HOST_FLAG = "[CHECK HOST]";

function authName(auth: Auth): string {
  const p = auth.parameterName;
  switch (auth.type) {
    case "api_key":
      if (auth.location === "query") return `Token in query (?${p ?? "api_key"}=)`;
      if (auth.location === "cookie") return `API key in cookie (${p ?? "cookie"})`;
      return `API key in header (${p ?? "X-API-Key"})`;
    case "bearer":
      return "Bearer token (Authorization header)";
    case "basic":
      return "HTTP Basic auth";
    case "oauth2":
      return "OAuth 2.0 access token";
    default:
      return auth.type;
  }
}

/** One sample request showing how to call the API with an alternative documented auth method. */
function buildAuthAlternative(
  method: AuthMethod,
  endpoints: UsableEndpoint[],
  baseUrl: string | null,
  credentialParams: Set<string>,
  apiJson: boolean,
) {
  const sample =
    endpoints.find((e) => e.value.method === "GET" && endpointTarget(e.value.path, baseUrl).kind === "relative") ?? endpoints[0];
  const base = sample
    ? buildItem(sample, endpointTarget(sample.value.path, baseUrl), credentialParams, apiJson)
    : buildItem(
        { status: "documented", value: { method: "GET", path: "/", purpose: "", keyParams: [] }, sources: [] },
        { kind: "relative", path: "/" },
        credentialParams,
        apiJson,
      );
  const request: Record<string, unknown> & typeof base.request = { ...base.request, header: [...base.request.header] };
  const { type, location, parameterName } = method.value;

  if (type === "api_key") {
    const name = parameterName ?? (location === "query" ? "api_key" : "X-API-Key");
    if (location === "query") {
      const url = request.url;
      request.url = {
        ...url,
        raw: `${url.raw}${url.raw.includes("?") ? "&" : "?"}${name}={{apiKey}}`,
        query: [...(url.query ?? []), { key: name, value: "{{apiKey}}", description: "Credential (documented auth method)" }],
      };
    } else if (location === "cookie") {
      request.header.push({ key: "Cookie", value: `${name}={{apiKey}}` });
    } else {
      request.header.push({ key: name, value: "{{apiKey}}" });
    }
    // Override the collection-level auth so only this method is used.
    request.auth = { type: "noauth" };
  } else {
    request.auth = toPostmanAuth(method.value)!;
  }

  request.description = [
    `Alternative auth: ${method.value.description}`,
    "",
    "Status: Documented",
    ...method.sources.map((s) => (s.quote ? `Source: ${s.url}\n"${s.quote}"` : `Source: ${s.url}`)),
  ].join("\n");

  return { name: `${authName(method.value)}: ${sample ? `${sample.value.method} ${sample.value.path}` : "GET /"}`, request, event: base.event };
}

function buildItem(ep: UsableEndpoint, target: EndpointTarget, credentialParams: Set<string>, apiJson: boolean) {
  const { method, path, purpose } = ep.value;
  // Credential params (e.g. ?token=) are supplied by the auth setup, not left empty on every request.
  const keyParams = ep.value.keyParams.filter((p) => !credentialParams.has(`${p.in}:${p.name.toLowerCase()}`));
  const postmanPath = toPostmanPath(target.path);
  const hostPrefix = target.kind === "absolute" ? target.origin : "{{baseUrl}}";
  const segments = postmanPath.split("/").filter(Boolean);
  const query = keyParams
    .filter((p) => p.in === "query")
    .map((p) => ({ key: p.name, value: "", description: p.description, ...(p.required ? {} : { disabled: true }) }));
  // Path variables are prefilled only with values from the docs' own example URLs (verified quotes).
  const examples = pathVariableExamples(ep);
  const pathVars = keyParams
    .filter((p) => p.in === "path")
    .map((p) => ({
      key: p.name,
      value: examples[p.name] ?? "",
      description: examples[p.name] ? `${p.description} (example value from the docs)` : p.description,
    }));
  const headerParams = keyParams.filter((p) => p.in === "header").map((p) => ({ key: p.name, value: "", description: p.description }));
  const bodyParams = keyParams.filter((p) => p.in === "body");

  const queryString = query.filter((q) => !q.disabled).map((q) => `${q.key}=`).join("&");
  const raw = `${hostPrefix}${postmanPath}${queryString ? `?${queryString}` : ""}`;

  // A body is set only when the docs show one (verified); a made-up body would look ready but fail.
  const exampleBody = BODY_METHODS.has(method) ? ep.value.exampleBody : undefined;
  const isJson = exampleBody !== undefined && parsesAsJson(exampleBody);
  const header = [{ key: "Accept", value: "application/json" }, ...headerParams];
  if (isJson) header.push({ key: "Content-Type", value: "application/json" });
  const bodyNote = !BODY_METHODS.has(method)
    ? []
    : exampleBody !== undefined
      ? ["Body: example copied from the docs (verified against the cited page)."]
      : [
          "Body: not set. The pages read show no example request body, so none was generated; check the docs before sending.",
          ...bodyParams.map((p) => `- ${p.name}${p.required ? " (required)" : ""}: ${p.description}`),
        ];

  const host = ep.hostCheck;
  const description = [
    ...(host?.status === "ambiguous"
      ? [
          `WARNING: host is ambiguous. The docs show this endpoint on: ${host.candidates.join(", ")}.`,
          `This request uses ${hostPrefix}; confirm the right host before relying on it.`,
          "",
        ]
      : []),
    purpose,
    "",
    `Status: ${STATUS_LABEL[ep.status]}`,
    ...(target.kind === "absolute" ? [`Note: this endpoint uses ${target.origin}, not {{baseUrl}}.`] : []),
    ...(host?.status === "corrected" ? [`Host taken from the docs' example URL: "${host.evidence}"`] : []),
    ...(ep.reasoning ? [`Reasoning: ${ep.reasoning}`] : []),
    ...(bodyNote.length ? ["", ...bodyNote] : []),
    ...ep.sources.map((s) => `Source: ${s.url}`),
  ].join("\n");

  return {
    name: `${host?.status === "ambiguous" ? `${CHECK_HOST_FLAG} ` : ""}${method} ${path}${ep.status === "inferred" ? " (inferred)" : ""}`,
    event: [testEvent(apiJson || endpointDocumentsJson(ep))],
    request: {
      method,
      header,
      url: {
        raw,
        ...(target.kind === "absolute"
          ? { protocol: target.origin.split(":")[0]!.toLowerCase(), host: target.host.split(".") }
          : { host: ["{{baseUrl}}"] }),
        path: segments,
        ...(query.length ? { query } : {}),
        ...(pathVars.length ? { variable: pathVars } : {}),
      },
      ...(exampleBody !== undefined
        ? { body: { mode: "raw", raw: exampleBody, options: { raw: { language: isJson ? "json" : "text" } } } }
        : {}),
      description,
    },
  };
}

export const DEFAULT_MAX_RESPONSE_MS = 5000;

const JSON_WORD = /\bjson\b/i;
/** "returns JSON", "responses are JSON", "JSON response": JSON as the response format. */
const JSON_RESPONSES = /\b(respon\w*|returns?|returned)\b[^.]{0,80}\bjson\b|\bjson\b[^.]{0,40}\brespon\w*/i;

/**
 * API-wide evidence that successful responses are JSON: a verified quote of a
 * documented finding that says so. Error-format quotes don't count (they
 * describe error bodies only).
 */
export function apiDocumentsJsonResponses(analysis: Analysis): boolean {
  const findings = [analysis.baseUrl, analysis.auth, ...analysis.authAlternatives, analysis.pagination, analysis.rateLimits, analysis.versioning];
  return findings.some((f) => f.status === "documented" && f.sources.some((s) => s.quote && JSON_RESPONSES.test(prose(s.quote))));
}

/** Quote text without URLs: "json" in https://x/8.8.8.8/json says nothing about the format. */
const prose = (quote: string) => quote.replace(/https?:\/\/\S+/gi, " ");

/** Endpoint-level evidence: a path ending in .json or /json, or a verified quote of the endpoint that mentions JSON. */
export function endpointDocumentsJson(ep: UsableEndpoint): boolean {
  if (/[./]json$/i.test(ep.value.path.split("?")[0]!.trim())) return true;
  return ep.status === "documented" && ep.sources.some((s) => s.quote && JSON_WORD.test(prose(s.quote)));
}

/**
 * Fixed test script for every request. Nothing from the docs is inserted
 * (model output never becomes code), and no response fields are assumed.
 */
function testEvent(expectJson: boolean) {
  const exec = [
    'pm.test("Status is 2xx", function () {',
    '  pm.expect(pm.response.code, "HTTP status").to.be.within(200, 299);',
    "});",
    `var maxResponseMs = Number(pm.variables.get("maxResponseMs")) || ${DEFAULT_MAX_RESPONSE_MS};`,
    'pm.test("Response time is under " + maxResponseMs + " ms", function () {',
    "  pm.expect(pm.response.responseTime).to.be.below(maxResponseMs);",
    "});",
  ];
  if (expectJson) {
    exec.push(
      "// The docs show JSON responses for this request, so the body must be JSON.",
      'pm.test("Response is JSON", function () {',
      '  pm.expect(pm.response.headers.get("Content-Type") || "", "Content-Type").to.include("json");',
      "  pm.response.json();",
      "});",
    );
  }
  return { listen: "test", script: { type: "text/javascript", exec } };
}

function parsesAsJson(text: string): boolean {
  try {
    JSON.parse(text);
    return true;
  } catch {
    return false;
  }
}

/** Postman auth block for a method, or null if Postman can't express it (none/other). */
function toPostmanAuth(auth: Auth): PostmanAuth | null {
  const { type, location, parameterName } = auth;
  switch (type) {
    case "api_key":
      if (location === "cookie") return null;
      return {
        type: "apikey",
        apikey: [
          { key: "key", value: parameterName || (location === "query" ? "api_key" : "X-API-Key"), type: "string" },
          { key: "value", value: "{{apiKey}}", type: "string" },
          // Postman's apikey auth supports header and query only; cookie keys go in the alternatives folder.
          { key: "in", value: location === "query" ? "query" : "header", type: "string" },
        ],
      };
    case "bearer":
      return { type: "bearer", bearer: [{ key: "token", value: "{{apiKey}}", type: "string" }] };
    case "basic":
      return {
        type: "basic",
        basic: [
          { key: "username", value: "{{apiKey}}", type: "string" },
          { key: "password", value: "", type: "string" },
        ],
      };
    case "oauth2":
      return {
        type: "oauth2",
        oauth2: [
          { key: "accessToken", value: "{{apiKey}}", type: "string" },
          { key: "addTokenTo", value: "header", type: "string" },
        ],
      };
    default:
      return null;
  }
}

function describeAuthGap(analysis: Analysis): string {
  if (analysis.auth.status === "not_found" || !analysis.auth.value) return "not found in docs; configure manually.";
  return `${analysis.auth.value.type}: ${analysis.auth.value.description} (${STATUS_LABEL[analysis.auth.status].toLowerCase()}, not documented, so not configured; set it up manually).`;
}

/** Environment template: baseUrl is public and prefilled when known; every credential is empty. */
export function buildPostmanEnvironment(analysis: Analysis, id: string = randomUUID()) {
  return {
    id,
    name: `${analysis.apiName} (template)`,
    values: [
      { key: "baseUrl", value: baseUrlOf(analysis) ?? "", type: "default", enabled: true },
      { key: "apiKey", value: "", type: "secret", enabled: true },
    ],
    _postman_variable_scope: "environment",
  };
}
